name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install pyinstaller

      - name: Build on Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile src/rechronos.py -n rechronos

      - name: Build on Windows
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --icon assets/rechronos.ico --uac-admin src/rechronos.py -n rechronos.exe

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/rechronos*
            dist/rechronos.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
