name: Build & Release reChronos

on:
  push:
    tags:
      - "v*0.9.2"   # Trigger khi có tag dạng vX.Y.Z

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      # Checkout code
      - name: Checkout repo
        uses: actions/checkout@v4

      # Setup Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # Install deps
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller pillow

      # Build binary
      - name: Build binary
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            pyinstaller --onefile src/rechronos.py -n rechronos
          else
            pyinstaller --onefile --icon assets/rechronos.ico --uac-admin src/rechronos.py -n rechronos.exe
          fi

      # Upload artifact (for debugging / manual download)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: rechronos-${{ matrix.os }}
          path: dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./dist

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
